theme = "zenwritten"

[editor]
line-number = "relative"
mouse = false
inline-completion-auto-trigger = true
end-of-line-diagnostics = "hint"
inline-completion-timeout = 150

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.insert]
C-a = "inline_completion_accept"
