[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]

[language-server.copilot]
command = "copilot-language-server"
args = ["--stdio"]

[language-server.copilot.config]
editorInfo = { name = "Helix", version = "25.01" }
editorPluginInfo = { name = "helix-copilot", version = "0.1.0" }

[[language]]
name = "rust"
language-servers = [ "harper-ls", "copilot", "rust-analyzer" ]

[[language]]
name = "toml"
language-servers = [ "harper-ls", "copilot", "taplo", "tombi" ]

[[language]]
name = "fish"
language-servers = [ "harper-ls", "copilot", "fish-lsp" ]

[[language]]
name = "json"
language-servers = [ "harper-ls", "copilot", "vscode-json-language-server" ]

[[language]]
name = "go"
language-servers = [ "harper-ls", "copilot", "gopls", "golangci-lint-lsp" ]

[[language]]
name = "gotmpl"
language-servers = [ "harper-ls", "copilot", "gopls" ]

[[language]]
name = "gowork"
language-servers = [ "harper-ls", "copilot", "gopls" ]

[[language]]
name = "javascript"
language-servers = [ "harper-ls", "copilot", "typescript-language-server" ]

[[language]]
name = "jsx"
language-servers = [ "harper-ls", "copilot", "typescript-language-server" ]

[[language]]
name = "typescript"
language-servers = [ "harper-ls", "copilot", "typescript-language-server" ]

[[language]]
name = "tsx"
language-servers = [ "harper-ls", "copilot", "typescript-language-server" ]

[[language]]
name = "css"
language-servers = [ "harper-ls", "copilot", "vscode-css-language-server" ]

[[language]]
name = "html"
language-servers = [ "harper-ls", "copilot", "vscode-html-language-server", "superhtml" ]

[[language]]
name = "python"
language-servers = [ "harper-ls", "copilot", "ty", "ruff", "jedi", "pylsp" ]

[[language]]
name = "bash"
language-servers = [ "harper-ls", "copilot", "bash-language-server" ]

[[language]]
name = "svelte"
language-servers = [ "harper-ls", "copilot", "svelteserver" ]

[[language]]
name = "yaml"
language-servers = [ "harper-ls", "copilot", "yaml-language-server", "ansible-language-server" ]

[[language]]
name = "markdown"
language-servers = [ "harper-ls", "copilot", "marksman", "markdown-oxide", "rumdl" ]

[[language]]
name = "dockerfile"
language-servers = [ "harper-ls", "copilot", "docker-langserver", "docker-language-server" ]

[[language]]
name = "tfvars"
language-servers = [ "harper-ls", "copilot", "terraform-ls" ]

[[language]]
name = "templ"
language-servers = [ "harper-ls", "copilot", "templ" ]
